codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        flags:
          - unittests

flags:
  unittests:
    paths:
      - pkg/

ignore:
  # Entrypoint — not testable
  - "main.go"
  - "internal/bootstrap/*"

  # Daemon binary packages (low value for unit tests)
  - "metrics-daemonset/*"
  - "poweroff-daemonset/*"
  - "wol-agent/*"
  
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
