defaultBaseImage: cgr.dev/chainguard/static:latest
defaultPlatforms:
  - linux/amd64
  - linux/arm64

builds:
- id: cluster-bare-autoscaler
  dir: .
  env:
  - CGO_ENABLED=0
  ldflags:
    - "-s -w"
    - -X cmd.version={{ .Git.Tag }} -X cmd.date={{ .Git.CommitTimestamp }} -X cmd.commit={{ .Git.FullCommit }}
