minNodes: 1
cooldown: 5m
pollInterval: 10s
ignoreLabels:
  node-role.kubernetes.io/control-plane: ""
nodes:
  - name: node2
    ip: 172.20.4.14
  - name: node3
    ip: 172.20.4.15
  - name: node4
    ip: 172.20.4.16
  - name: node5
    ip: 172.20.4.17
  - name: node14
    ip: 172.20.4.20
  - name: node16
    ip: 172.20.4.22
  - name: node17
    ip: 172.20.4.23
  - name: node18
    ip: 172.20.4.24
  - name: node19
    ip: 172.20.4.25
  - name: node22
    ip: 172.20.4.21