logLevel: debug
minNodes: 3
cooldown: 60m
bootCooldown: 360m
pollInterval: 60s
dryRun:
resourceBufferCPUPerc: 10
resourceBufferMemoryPerc: 10
bootstrapCooldownSeconds: 30
ignoreLabels:
  node-role.kubernetes.io/control-plane: ""
  ignore-this-node: yes
loadAverageStrategy:
  enabled: true
  nodeThreshold: 0.7
  clusterWideThreshold: 0.5
  podLabel: "app=cluster-bare-autoscaler-sysmetrics"
  namespace: cluster-bare-autoscaler
  port: 9100
  timeoutSeconds: 3
  clusterEval: p75
shutdownManager:
  port: 9101
  namespace: cluster-bare-autoscaler
  podLabel: cluster-bare-autoscaler-poweroff-manager
shutdownMode: "http"

powerOnMode: "wol"
wolBroadcastAddr: 192.168.0.255
wolBootTimeoutSeconds: 600 # 10mins
wolAgent:
  enabled: true
  port: 9102
  namespace: cluster-bare-autoscaler
  podLabel: cluster-bare-autoscaler-wol-agent

nodes:
  - name: workernode1
    ip: 192.168.0.10
    wolMacAddr: xx:xx:xx:xx:xx:xx
  - name: workernode2
    ip: 192.168.0.11
    wolMacAddr: xx:xx:xx:xx:xx:xx
  - name: workernode3
    ip: 192.168.0.12
    wolMacAddr: xx:xx:xx:xx:xx:xx
  - name: workernode4
    ip: 192.168.0.13
    wolMacAddr: xx:xx:xx:xx:xx:xx
  - name: workernode5
    ip: 192.168.0.14
    wolMacAddr: xx:xx:xx:xx:xx:xx