apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-bare-autoscaler.fullname" . }}-config
data:
  config.yaml: |
    logLevel: {{ .Values.logLevel }}
    minNodes: {{ .Values.minNodes }}
    cooldown: {{ .Values.cooldown }}
    pollInterval: {{ .Values.pollInterval }}
    resourceBufferCPUPerc: {{ .Values.resourceBuffer.cpuPerc }}
    resourceBufferMemoryPerc: {{ .Values.resourceBuffer.memoryPerc }}
    ignoreLabels:
    {{- range $key, $val := .Values.ignoreLabels }}
      {{ $key }}: "{{ $val }}"
    {{- end }}
    nodes:
    {{- range .Values.nodes }}
      - name: {{ .name }}
        ip: {{ .ip }}
    {{- end }}
