apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-bare-autoscaler.fullname" . }}
  labels:
    app: {{ include "cluster-bare-autoscaler.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cluster-bare-autoscaler.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cluster-bare-autoscaler.name" . }}
    spec:
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: autoscaler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - --config=/etc/autoscaler/config.yaml
            {{- if .Values.dryRun }}
            - --dry-run
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/autoscaler
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources: {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "cluster-bare-autoscaler.fullname" . }}-config
