apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cba-to-metrics
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: cluster-bare-autoscaler-sysmetrics
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "cluster-bare-autoscaler.name" . }}
      ports:
        - protocol: TCP
          port: 9100
