replicaCount: 1

image:
  repository: docent/cluster-bare-autoscaler
  tag: "0.1.2-dirty"
  pullPolicy: IfNotPresent

imagePullSecrets: []
priorityClassName: "system-cluster-critical"

logLevel: debug
pollInterval: 10s
cooldown: 5m
minNodes: 7
dryRun: true

resourceBuffer:
  cpuPerc: 5
  memoryPerc: 5

resources:
  limits:
    cpu: 250m
    memory: 32Mi
  requests:
    cpu: 100m
    memory: 16Mi

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

ignoreLabels:
  node-role.kubernetes.io/control-plane: ""
  node-home-assistant: "yes"

serviceAccount:
  create: false
  name: cluster-bare-autoscaler

rbac:
  create: false

nodes:
  - name: node1
    ip: 192.168.0.1
  - name: node2
    ip: 192.168.0.2
  - name: node3
    ip: 192.168.0.3
  - name: node4
    ip: 192.168.0.4

metricsDaemonset:
  enabled: true
  image:
    repository: docent/loadavg-exporter
    tag: v0.1.0
    pullPolicy: IfNotPresent
  port: 9100
  imagePullSecrets: []
  priorityClassName: "system-cluster-critical"
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
  tolerations: []
  nodeSelector: {}
  podLabels: {}
